### ISSUE TITLE
can't download DIVIO APP

### ISSUE THREAD

**Issue by oneofsunshine** [divio/djangocms-history#15]
I'm following **Basic: How to build a website and blog with django CMS (60 minutes)**. And when I come to **step 2: Installing the Divio App**, I can't download the `appimage`, could you tell me what should i do to deal with it. Thank you！ 
_ps:_ english is not my first-language, please forgive my poor english~_

**Comment by czpython** [comment]
Hello,
For Divio Cloud questions/support, please contact us through the intercom bubble (at the bottom right) in https://www.divio.com/en/#intercom
