### ISSUE TITLE
djangocms-history vs. djangocms-versioning

### ISSUE THREAD

**Issue by jedie** [divio/djangocms-history#28]
Is djangocms-versioning the successor of djangocms-history?

So is this project discontinued?

**Comment by FinalAngel** [comment]
@jedie djangocms-versioning is in early stage of development, there are no plans to discontinue djangocms-history for the 3.x branch. We will soon release 3.6 and 3.7 will be our next LTS.

djangocms-versioning might be a part of django CMS 4 which may have several breaking changes.

**Comment by jedie** [comment]
that's nice to hear.

I think https://www.django-cms.org/en/roadmap/ should be updated as well ;)

**Comment by FinalAngel** [comment]
Yes :) we probably should reformat it a bit 👍
