### ISSUE TITLE
Undo/Redo disabled on i18n enabled website and page language distinct from user language

### ISSUE THREAD

**Issue by rolandf** [divio/djangocms-history#32]
I have a djangocms project with french and english.
Strangely the english pages have undo/redo toolbar button disabled at all time.
French pages have undo once I modify plugins and undo work.
(Edit: my user was set to french)

The undo/redo history function work when the language of the page matches the language of the current logged in user.
If in my settings I activate french, I can undo/redo french pages but not pages in english.
If in my settings I activate english, I can undo/redo english pages but not pages in french.

I would have expected to be able to undo/redo changes on all language versions of pages.

I'm using Python 3.6.9, Django 2.2.1, django-cms 3.7.1 and djangocms-history 1.1.0.

**Comment by rolandf** [comment]
In two places in cms_toolbar.py there is the following block:
`if CMS_GTE_36:
            toolbar_language = self.toolbar.toolbar_language
        else:
            toolbar_language = self.toolbar.language
`

I left it in place and added just bellow
`        toolbar_language = self.current_lang`

And the undo redo mechanism work in both language but only if I stay on the same language version.
Once I switch, the undo/redo queue is cleared.

I'm not sure if this is good but a small step toward understanding how it work.

**Comment by FinalAngel** [comment]
This is actually intended behaviour. The undo/redo functionality only works for your current session in that language. Once you switch it is cleared. When you change that setting this is broken and introduces side-effects. Undo/Redo is not meant as a version control system but rather a short term "live saver" :D
