### ISSUE TITLE
Template files are not installed by pip install

### ISSUE THREAD

**Issue by FabriceSalvaire** [divio/djangocms-history#6]
Django CMS cpmplains about missing templates/djangocms_history/toolbar/ajax_button.html

**Comment by czpython** [comment]
Hello, did you add djangocms_history to your `INSTALLED_APPS`?

**Comment by FabriceSalvaire** [comment]
yes and I verified this file is missing in my virtual env.

**Comment by czpython** [comment]
Strange.. can you post the exact command used to install this?

**Comment by FabriceSalvaire** [comment]
pip install git+git://github.com/divio/djangocms-history#egg=djangocms-history

**Comment by czpython** [comment]
Thanks for this.
It's been fixed on master branch.
